import numpy as np


def LCS_Length(X,Y):

    m , n = len(X), len(Y)
    c , b = np.zeros((m+1,n+1)), np.zeros((m+1,n+1))

    for i in range(m):
        for j in range(n):
            
            if X[i] == Y[j]:
                c[i+1,j+1] = c[i,j] + 1 
                b[i+1,j+1] = 1
            
            elif c[i,j+1] >= c[i+1,j]:
                c[i+1,j+1] = c[i,j+1]
                b[i+1,j+1] = 2
            
            else:
                c[i+1,j+1] = c[i+1,j]
                b[i+1,j+1] = 3 
    
    print(c)
    # print('\n')
    # print(b)

    return c,b

def Print_LCS(b,X,i,j,lcs):

    if i==0 or j==0 :
        return 
    
    if b[i,j] == 1 :
        Print_LCS(b,X,i-1,j-1,lcs)
        lcs.append(X[i-1])
    
    elif b[i,j] == 2 :
        Print_LCS(b,X,i-1,j,lcs)

    else:
        Print_LCS(b,X,i,j-1,lcs) 




if __name__ == '__main__':
    
    X = 'ABCBDAB'
    Y = 'BDCABA'
    lcs = []

    c,b = LCS_Length(X,Y)

    print('\n')
    Print_LCS(b,X,len(X),len(Y),lcs)
    print(lcs)
    print('Porcentaje de coincidencia: {}%'.format(round((len(lcs)/len(X))*100,2)))


    print('\n\nEjercicio 1\n')

    X = 'ACAAGATGCCATTGTCCCCCGGCCTCCTGCTGCTGCTGCTCTCCGGGGCCACGGCCACCGCTGCCCTGCCCCTGGAGGGTGGCCCCACCGGCCGAGACAGCGAGCATATGCAGGAAGCGGCAGGAATAAGGAAAAGCAGCCTCCTGACTTTCCTCGCTTGGTGGTTTGAGTGGACCTCCCAGGCCAGTGCCGGGCCCCTCATAGGAGAGGAAGCTCGGGAGGTGGCCAGGCGGCAGGAAGGCGCACCCCCCCAGCAATCCGCGCGCCGGGACAGAATGCCCTGCAGGAACTTCTTCTGGAAGACCTTCTCCTCCTGCAAATAAAACCTCACCCATGAATGCTCACGCAAGTTTAATTACAGACCTGAA'
    Y = 'CCTCCTGCGGAGGGTATATGGCTTTCGGGACAGAAATACCTG'
    lcs = []

    c,b = LCS_Length(X,Y)

    print('\n')
    Print_LCS(b,X,len(X),len(Y),lcs)
    print(lcs)
    print('Porcentaje de coincidencia: {}%'.format(round((len(lcs)/len(X))*100,2)))


    print('\n\nEjercicio 2\n')

    X = 'ACAAGATGCCATTGTCCCCCGGCCTCCTGCTGCTGCTGCTCTCCGGGGCCACGGCCACCGCTGCCCTGCCCCTGGAGGGTGGCCCCACCGGCCGAGACAGCGAGCATATGCAGGAAGCGGCAGGAATAAGGAAAAGCAGCCTCCTGACTTTCCTCGCTTGGTGGTTTGAGTGGACCTCCCAGGCCAGTGCCGGGCCCCTCATAGGAGAGGAAGCTCGGGAGGTGGCCAGGCGGCAGGAAGGCGCACCCCCCCAGCAATCCGCGCGCCGGGACAGAATGCCCTGCAGGAACTTCTTCTGGAAGACCTTCTCCTCCTGCAAATAAAACCTCACCCATGAATGCTCACGCAAGTTTAATTACAGACCTGAAACAAGATGCCATTGTCCCCCGGCCTCCTGCTGCTGCTGCTCTCCGGGGCCACGGCCACCGCTGCCCTGCCCCTGGAGGGTGGCCCCACCGGCCGAGACAGCGAGCATATGCAGGAAGCGGCAGGAATAAGGAAAAGCAGCCTCCTGACTTTCCTCGCTTGGTGGTTTGAGTGGACCTCCCAGGCCAGTGCCGGGCCCCTCATAGGAGAGGAAGCTCGGGAGGTGGCCAGGCGGCAGGAAGGCGCACCCCCCCAGCAATCCGCGCGCCGGGACAGAATGCCCTGCAGGAACTTCTTCTGGAAGACCTTCTCCTCCTGCAAATAAAACCTCACCCATGAATGCTCACGCAAGTTTAATTACAGACCTGAA'
    Y = 'GACTTTTTTTTTTTTTCCTTTGGGAAAGGTACAAGATGCCATTGTCCGCTGCTGCTCTCCGGGGCCACGGCCACCGCTGCCCTGCCCCTGGAGGGTGGCCCCACCGGCATATGCAGGAAGCGGCAGGAAACAAGATGCCATTGTCTCCTGCTGCTGCTGCTCTCCGGGGCCACGGCCACCGCTGCCCTGCCCCTGGAGGGTGGCCCCACCGGCCGAGACAGCGAGCATATGCAGGAAAAGGAAAAGCAGCCTCCTGCGCTTGGTGGTTTGAGTGGACCTCCCAGGCCAGTGCCGGGCCCCTCATAGGAGAGGAAGCTCGGGAGGTGGCCAGGCGGAGCAATCCGCGCGCCGGGACAGAATGCCCTGCAGGAACCTTCTCCTCCTGCAAATAAAACCTCACCCATGGCAAGGGTCTCCAAACTTTTCCTGGTTCTTTATATCTTCAGGTATTCCTCTCCCCTTTAATTACAGACCTGAA'
    lcs = []

    c,b = LCS_Length(X,Y)

    print('\n')
    Print_LCS(b,X,len(X),len(Y),lcs)
    print(lcs)
    print('Porcentaje de coincidencia: {}%'.format(round((len(lcs)/len(X))*100,2)))


    print('\n\nEjercicio 3\n')

    X = 'GACTTTTTTTTTTTTTCCTTTGGGAAAGGTAGGGAGGTGTTCGTACGGGAGCAGCCTCGGGGACCCCTGCACTGGGTCAGGGCTTATGAAGCTAGAAGCGTCCCTCTGTTCCCTTTGTGAGTTGGTGGGTTGTTGGTACATTTGGTTGGAAGCTGTGTTGCTGGTTAGGGAGACTCGGTTTTGCTCCTTGGGTTCGAGGAAAGCTGGAGAATAGAAGCCATTGTTTGCCGTCTGTCGGCTTTGTCGACCACGCTCACCCCCTCCTGTTCGTACTTTTTAAAGCAGTGAGGCGAGGTAGACAGGGTGTGTCACAGTACAGTTAAAGGGGTGAAGATCTAAACGCCAAAAGAGAAGTTAATCACAATAAGTGAGGTTTGGGATAAAAAGTTGGGCTTGCCCCTTTCAAAGTCCCAGAAAGCTGGGAGGTAGATGGAGAGGGGGCCATTGGGAAGTTTTTTTGGTGTAGGGAGAGGAGTAGAAGATAAAGGGTAAGCAGAGTGTTGGGTTCTGGGGGTCTTGTGAAGTTCCTTAAGGAAGGAGGGAGTGTGGCCCTGCAGCCCTCCCAAACTGCTCCAGCCTATGCTCTCCGGCACCAGGAAGTTCCAAGGTTCCCTTCCCCTGGTCTCCAAACTTCAGGTATTCCTCTCCCCTCACACCCCTTCAACCTCAGCTCTTGGCCTCTACTCCTTACTCCACTGTTCCTCCTGTTTCCCCCTTCCCCTTTTCCTGGTTCTTTATATTTTTGCAAAGTGGGATCCGAACTTGCTAGATTTTCCAATTCTCCCAAGCCAGACCAGAGCAGCCTCTTTTAAAGGATGGAGACTTCTGTGGCAGATGCCGCTGAAAATGTGGGTGTAATGCTGGGACTTAGAGTTTGATGACAGTTTGACTGAGCCCTAGATGCATGTGTTTTTCCTGAGAGTGAGGCTCAGAGAGCCCATGGACGTATGCTGTTGAACCACAGCTTGATATACCTTTTTCTCCTTCTGTTTTGTCTTAGGGGGAAGACTTTAACTAGGGGCGCGCAGATGTGTGAGGCCTTTTATTGTGAGAGTGGACAGACATCCGAGATTTCAGGCAAGTTCTGTGGTGGCTGCTTTGGGCT'
    Y = 'TTTCCTGGTTCTTTATATTTTTGCAAAGTGGGATCCGAACTTTTTTTTTTTTTTTTCCCCCAAAAAAAGAGAGGGGGCCCCCCTTCCCCTTTTCCTGGTTCTTTATATTTTTGTTGTCTTAGGGGGAAGACCTCCTGCGGAGGGTATATGGCTTTCGGGACAGAAATACCTG'
    lcs = []

    c,b = LCS_Length(X,Y)

    print('\n')
    Print_LCS(b,X,len(X),len(Y),lcs)
    print(lcs)
    print('Porcentaje de coincidencia: {}%'.format(round((len(lcs)/len(X))*100,2)))